config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users do 
    resources :items
  end
  resources :sessions

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items 
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :after_sign_in_path

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def after_sign_in_path(user)
    user_path(user)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new 
    @user = current_user
    @item = Item.new 
  end 
  def create
    @user = current_user 
    @item = @user.items.create(item_params)
    @item.save! 
    redirect_to user_path(@user) 
  end

  def destroy  
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html
      format.js   #{ render :layout => false }
    end
  end 

  private 

  def item_params
    params.require(:item).permit(:name)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to after_sign_in_path(user), :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def edit
   @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to after_sign_in_path(@user), :notice => "Signed up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items 
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to root_url, :notice => "Success in editing is yours!"
    else
      render "new"
    end
  end

  private 

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<div class = "col-md-8 text-center center">
  <%= form_for [@user, @item] do |f| %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name , class: 'form-control'%>
    </p>

    <p><%= f.submit %></p>
  <% end %>
</div>

app/views/items/_item.html.erb
<tr> 
  <td> <%= item.name %> </td> 
  <td> <%=item.days_left%></td>  
  <td> <%= link_to "", user_item_path(current_user, item), method: :delete, class: 'glyphicon glyphicon-ok delete_row', remote: true%></td>
</tr> 

app/views/items/destroy.js.erb
$('.delete_row').bind("ajax:success", function(){
  $(this).closest("tr").fadeOut()
});

app/views/items/new.html.erb
<h1>Create your items!</h1>

<%= render partial: 'form' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container center text-center">
    <div id="user_nav">
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log out", log_out_path %>
      <%= link_to "Edit account", edit_user_path(current_user) %>
    <% else %>
      <%= link_to "Sign up", sign_up_path %> or
      <%= link_to "log in", log_in_path %>
    <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/edit.html.erb
<h1>Edit Account for <%= current_user.email %></h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.email %>'s Items </h1> 
<table class = "table"> 
<tr>
  <th> Name </th> 
  <th> Days Left </td>  
  <th> Done? </td> 
</tr> 
<%= render @items %> <!-- render partial: 'lunches/lunch_form', locals: {lunch: @daily_lunch }  -->
</table>